# Generated by Django 5.2.8 on 2025-11-07 22:21

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_contacto_rol_delete_post_contacto_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='idRol',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Ingrese el ID de un rol existente', null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='Ejemplo: +504 1111-1111', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ejemplo: +504 1111-1111', regex='^\\+?\\d{3,4}[-\\s]?\\d{4,}$')]),
        ),
        migrations.AddField(
            model_name='rol',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='region',
            field=models.CharField(default='', help_text='Región (máximo 10 caracteres)', max_length=10, validators=[django.core.validators.MaxLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
