# Generated by Django 5.2.8 on 2025-11-10 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_contacto_correo_contacto_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='contacto',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='Ejemplo: +504 31821111', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ejemplo: +504 31821111', regex='^\\+?\\d{3,4}[-\\s]?\\d{4,}$')]),
        ),
    ]
