# Generated by Django 5.2.8 on 2025-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_contacto_contacto_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='region',
            field=models.CharField(choices=[('LATAM', 'Latinoamérica'), ('USA', 'Estados Unidos'), ('EMEA', 'Europa, Medio Oriente y África'), ('APAC', 'Asia-Pacífico'), ('OTRA', 'Otra')], default='LATAM', help_text='Región', max_length=10),
        ),
    ]
