# Generated by Django 5.2.8 on 2025-11-11 20:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_rol_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='region',
            field=models.CharField(choices=[('IMHN', 'IMHN'), ('IMGT', 'IMGT'), ('IMCR', 'IMCR'), ('IMSL', 'IMSL'), ('CA', 'CA')], default='IMHN', help_text='Región', max_length=10),
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_mensaje', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensajes_enviados', models.PositiveIntegerField(default=0)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='dashboard.contacto')),
                ('conversacion_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siguiente_conversacion', to='dashboard.conversacion')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
