# Generated by Django 5.2.8 on 2025-11-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('arte', models.FileField(blank=True, null=True, upload_to='campanias/')),
                ('accion', models.URLField(blank=True, max_length=300, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('fechaProgramada', models.DateTimeField(blank=True, null=True)),
                ('exclusiones', models.ManyToManyField(blank=True, to='dashboard.contacto')),
            ],
        ),
    ]
