# Generated by Django 5.2.8 on 2025-11-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_campania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='exclusiones',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.contacto'),
        ),
    ]
